
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xclk_wiz.h"

/*
* The configuration table for devices
*/

XClk_Wiz_Config XClk_Wiz_ConfigTable[XPAR_XCLK_WIZ_NUM_INSTANCES] =
{
	{
		XPAR_VIDEO_OUT_CLK_WIZ_0_DEVICE_ID,
		XPAR_VIDEO_OUT_CLK_WIZ_0_BASEADDR,
		XPAR_VIDEO_OUT_CLK_WIZ_0_ENABLE_CLOCK_MONITOR,
		XPAR_VIDEO_OUT_CLK_WIZ_0_ENABLE_USER_CLOCK0,
		XPAR_VIDEO_OUT_CLK_WIZ_0_ENABLE_USER_CLOCK1,
		XPAR_VIDEO_OUT_CLK_WIZ_0_ENABLE_USER_CLOCK2,
		XPAR_VIDEO_OUT_CLK_WIZ_0_ENABLE_USER_CLOCK3,
		XPAR_VIDEO_OUT_CLK_WIZ_0_REF_CLK_FREQ,
		XPAR_VIDEO_OUT_CLK_WIZ_0_USER_CLK_FREQ0,
		XPAR_VIDEO_OUT_CLK_WIZ_0_USER_CLK_FREQ1,
		XPAR_VIDEO_OUT_CLK_WIZ_0_USER_CLK_FREQ2,
		XPAR_VIDEO_OUT_CLK_WIZ_0_USER_CLK_FREQ3,
		XPAR_VIDEO_OUT_CLK_WIZ_0_PRECISION,
		XPAR_VIDEO_OUT_CLK_WIZ_0_ENABLE_PLL0,
		XPAR_VIDEO_OUT_CLK_WIZ_0_ENABLE_PLL1
	}
};


