
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxis_switch.h"

/*
* The configuration table for devices
*/

XAxis_Switch_Config XAxis_Switch_ConfigTable[XPAR_XAXIS_SWITCH_NUM_INSTANCES] =
{
	{
		XPAR_CSI_RX_0_AXIS_SWITCH_0_DEVICE_ID,
		XPAR_CSI_RX_0_AXIS_SWITCH_0_BASEADDR,
		XPAR_CSI_RX_0_AXIS_SWITCH_0_NUM_SI,
		XPAR_CSI_RX_0_AXIS_SWITCH_0_NUM_MI
	},
	{
		XPAR_CSI_RX_1_AXIS_SWITCH_0_DEVICE_ID,
		XPAR_CSI_RX_1_AXIS_SWITCH_0_BASEADDR,
		XPAR_CSI_RX_1_AXIS_SWITCH_0_NUM_SI,
		XPAR_CSI_RX_1_AXIS_SWITCH_0_NUM_MI
	},
	{
		XPAR_MEMORY_SUBSYSTEM_AXIS_SWITCH_0_DEVICE_ID,
		XPAR_MEMORY_SUBSYSTEM_AXIS_SWITCH_0_BASEADDR,
		XPAR_MEMORY_SUBSYSTEM_AXIS_SWITCH_0_NUM_SI,
		XPAR_MEMORY_SUBSYSTEM_AXIS_SWITCH_0_NUM_MI
	}
};


