
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_PROCESSOR_SUBSYSTEM_RS485_HIER_AXI_GPIO_0_DEVICE_ID,
		XPAR_PROCESSOR_SUBSYSTEM_RS485_HIER_AXI_GPIO_0_BASEADDR,
		XPAR_PROCESSOR_SUBSYSTEM_RS485_HIER_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_PROCESSOR_SUBSYSTEM_RS485_HIER_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_XGPIO_I2C_0_AXI_GPIO_0_DEVICE_ID,
		XPAR_XGPIO_I2C_0_AXI_GPIO_0_BASEADDR,
		XPAR_XGPIO_I2C_0_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_XGPIO_I2C_0_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_MEMORY_SUBSYSTEM_V_PROC_SS_0_RESET_SEL_AXIS_DEVICE_ID,
		XPAR_MEMORY_SUBSYSTEM_V_PROC_SS_0_RESET_SEL_AXIS_BASEADDR,
		XPAR_MEMORY_SUBSYSTEM_V_PROC_SS_0_RESET_SEL_AXIS_INTERRUPT_PRESENT,
		XPAR_MEMORY_SUBSYSTEM_V_PROC_SS_0_RESET_SEL_AXIS_IS_DUAL
	}
};


